# This file is part of gsnap.
#
# This program is free software: you can redistribute it and/or modify it under
# the  terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see
#
#  http://www.gnu.org/licenses/
#
#
# Copyright (C) 2019 mksec <support@mksec.de>

stages:
  - build

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends
        dpkg-dev
        build-essential
        debhelper
  script:
    - dpkg-buildpackage -us -uc
    - mkdir packages
    - mv ../*.deb packages
  artifacts:
    paths:
      - packages/*
